// scripts/lib/design_system.js — the one Apple ("Cupertino") design system for
// every Node-rendered client report. Reads design-system/smos-design-system.css
// at render time so there is a SINGLE source of truth: edit the .css once and
// every deliverable (audit, weekly, monthly, before/after, analyze) inherits it.
//
// Usage:
//   import { designSystemCss, reportHead, heroHeader, reportFooter } from "./design_system.js";
//   const html = `<!DOCTYPE html><html lang="en">${reportHead({title})}
//     <body><div class="ds-wrap">${heroHeader({title, subtitle})} ... ${reportFooter()}</div></body></html>`;

import { readFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..", "..");
const CSS_PATH = resolve(ROOT, "design-system", "smos-design-system.css");

let _css = null;
/** The canonical design-system CSS as a string (cached after first read). */
export function designSystemCss() {
  if (_css === null) _css = readFileSync(CSS_PATH, "utf8");
  return _css;
}

const esc = (s) => String(s)
  .replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
  .replace(/"/g, "&quot;");

/** Full <head> with the design system inlined plus any extra <head> tags (e.g. Chart.js). */
export function reportHead({ title = "smOS Report", extraHead = "" } = {}) {
  return `<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(title)}</title>
${extraHead}
<style>${designSystemCss()}</style>
</head>`;
}

/** The standard blue gradient hero used at the top of every report. */
export function heroHeader({ title, subtitle = "", eyebrow = "" } = {}) {
  return `<header class="ds-hero">
${eyebrow ? `<div class="ds-eyebrow">${esc(eyebrow)}</div>` : ""}
<h1>${esc(title)}</h1>
${subtitle ? `<div class="ds-meta">${esc(subtitle)}</div>` : ""}
</header>`;
}

/** Standard footer. Pass an ISO date string (callers avoid new Date() in workflows). */
export function reportFooter(date = new Date().toISOString().slice(0, 10)) {
  return `<footer class="ds-footer">Generated by smOS · ${esc(date)}</footer>`;
}
