// scripts/lib/design_system.js — the one Apple ("Cupertino") design system for
// every Node-rendered client report. Reads design-system/smos-design-system.css
// at render time so there is a SINGLE source of truth: edit the .css once and
// every deliverable (audit, weekly, monthly, before/after, analyze) inherits it.
//
// Usage:
//   import { designSystemCss, reportHead, heroHeader, reportFooter } from "./design_system.js";
//   const html = `<!DOCTYPE html><html lang="en">${reportHead({title})}
//     <body><div class="ds-wrap">${heroHeader({title, subtitle})} ... ${reportFooter()}</div></body></html>`;

import { readFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..", "..");
const CSS_PATH = resolve(ROOT, "design-system", "smos-design-system.css");

let _css = null;
/** The canonical design-system CSS as a string (cached after first read). */
export function designSystemCss() {
  if (_css === null) _css = readFileSync(CSS_PATH, "utf8");
  return _css;
}

const esc = (s) => String(s)
  .replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
  .replace(/"/g, "&quot;");

/** Full <head> with the design system inlined plus any extra <head> tags (e.g. Chart.js). */
export function reportHead({ title = "smOS Report", extraHead = "" } = {}) {
  return `<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(title)}</title>
${extraHead}
<style>${designSystemCss()}</style>
</head>`;
}

/**
 * The ONE canonical report hero. Every client-facing report renders this exact
 * markup — never hand-roll a <header class="ds-hero"> or a bespoke .hero.
 *
 *  title    — required headline
 *  subtitle — `·`-separated meta line
 *  eyebrow  — badge pill text (e.g. agency name / report type)
 *  headline — optional one-line summary under the title
 *  pills    — optional array of short snapshot strings
 *  aside    — optional pre-rendered HTML for the right-hand executive column
 *             (e.g. a score ring + hero stat); pass via heroAside().
 */
export function heroHeader({ title, subtitle = "", subtitleHtml = "", eyebrow = "", headline = "", pills = [], aside = "" } = {}) {
  const pillsHtml = pills.length
    ? `<div class="ds-hero__pills">${pills.map((p) => `<span class="ds-hero__pill">${esc(p)}</span>`).join("")}</div>`
    : "";
  // subtitleHtml is trusted HTML (caller escapes dynamic parts); subtitle is escaped.
  const metaInner = subtitleHtml || (subtitle ? esc(subtitle) : "");
  return `<header class="ds-hero">
<div class="ds-hero__inner${aside ? " has-aside" : ""}">
<div class="ds-hero__main">
${eyebrow ? `<div class="ds-hero__badge">${esc(eyebrow)}</div>` : ""}
<h1>${esc(title)}</h1>
${metaInner ? `<div class="ds-meta">${metaInner}</div>` : ""}
${headline ? `<div class="ds-hero__headline">${esc(headline)}</div>` : ""}
${pillsHtml}
</div>
${aside ? `<div class="ds-hero__aside">${aside}</div>` : ""}
</div>
</header>`;
}

/** Build the optional right-hand hero column: an HTML body (e.g. a score ring)
 *  plus an optional single hero stat (label / value / caption). */
export function heroAside({ body = "", statLabel = "", statValue = "", statCaption = "" } = {}) {
  const stat = statValue
    ? `<div class="ds-hero__stat">
${statLabel ? `<div class="ds-hero__stat-label">${esc(statLabel)}</div>` : ""}
<div class="ds-hero__stat-value">${esc(statValue)}</div>
${statCaption ? `<div class="ds-hero__stat-caption">${esc(statCaption)}</div>` : ""}
</div>`
    : "";
  return `${body}${stat}`;
}

/** Standard footer. Pass an ISO date string (callers avoid new Date() in workflows). */
export function reportFooter(date = new Date().toISOString().slice(0, 10)) {
  return `<footer class="ds-footer">Generated by smOS · ${esc(date)}</footer>`;
}
