#!/usr/bin/env node
/**
 * /contract companion (Phase 5) — generates the service agreement from an accepted
 * proposal, optionally sends it for e-signature, and on signature advances the CRM
 * deal to `won`.
 *
 * Honest about scope, like the rest of smOS:
 *  - The contract is a TEMPLATE, not legal advice — output says so; have an attorney review.
 *  - E-sign is best-effort: with a provider key set it attempts a real send; otherwise
 *    it falls back to a manual signature block. (Live provider call is unverified — it
 *    fail-closes to manual on any error rather than pretending it sent.)
 *
 * Usage:
 *   node skills/contract/contract.js <slug> [--package growth]   # generate + link to CRM
 *   node skills/contract/contract.js <slug> --send               # also send for e-signature
 *   node skills/contract/contract.js <slug> --mark-signed        # record signature → deal won
 */
import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { loadEnv } from "../../scripts/lib/load-env.js";
import { heroHeader } from "../../scripts/lib/design_system.js";
import { docShell, writeDocHtmlAndPdf, docSection, escHtml } from "../../scripts/lib/client_doc.js";
import { getDeal, upsertDeal } from "../../scripts/lib/crm-store.js";
import { deal as dealSchema } from "../../schemas/index.js";
import { loadCatalog, pickPackage } from "../proposal/proposal.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "../..");
loadEnv();

const nowIso = () => new Date().toISOString();
const today = () => nowIso().slice(0, 10);

export function buildContractMarkdown({ agency, client, pkg, retainer, terms, date, addons, currency }) {
  const cur = currency || pkg.currency;
  const monthly = retainer > 0 ? retainer : pkg.monthly_retainer;
  let md = `# Social Media Management Agreement\n\n`;
  md += `*Effective ${date}*\n\n`;
  md += `> Template generated by smOS. This is not legal advice — have a qualified attorney review before signing.\n\n---\n\n`;

  md += `## 1. Parties\n\n`;
  md += `This agreement is between **${agency.name}** ("Agency", ${agency.email}) and **${client.company}** ("Client"${client.contact_name ? `, represented by ${client.contact_name}` : ""}${client.contact_email ? `, ${client.contact_email}` : ""}).\n\n`;

  md += `## 2. Services\n\n`;
  md += `Agency will provide the **${pkg.name}** package:\n\n${(pkg.includes || []).map((i) => `- ${i}`).join("\n")}\n\n`;

  md += `## 3. Fees\n\n`;
  md += `- **Monthly management retainer:** ${cur} ${monthly.toLocaleString()}, due monthly in advance.\n`;
  md += `- **One-time setup fee:** ${cur} ${(pkg.setup_fee || 0).toLocaleString()}, due on signing.\n`;
  if (addons && addons.length) {
    md += `- **One-time deliverables (due on signing, separate from the monthly retainer):**\n`;
    addons.forEach((a) => { md += `  - ${a.name}: ${(a.currency || cur)} ${(a.amount || 0).toLocaleString()}\n`; });
  }
  md += `- **Ad spend:** ${terms.ad_spend}\n\n`;

  md += `## 4. Term & Renewal\n\n`;
  md += `Initial term of **${terms.contract_length_months} months** from the effective date, renewing month-to-month thereafter unless cancelled.\n\n`;

  md += `## 5. Payment\n\n${terms.payment}\n\n`;
  md += `## 6. Cancellation\n\n${terms.cancellation}\n\n`;

  md += `## 7. Intellectual Property\n\n`;
  md += `Client owns its ad accounts, pages, pixels, brand assets, and all work product delivered and paid for. Agency retains ownership of its tools, processes, and the smOS platform used to deliver the services.\n\n`;

  md += `## 8. Confidentiality\n\n`;
  md += `Each party will keep the other's non-public information confidential and use it only to perform this agreement.\n\n`;

  md += `## 9. Limitation of Liability\n\n`;
  md += `Agency's total liability under this agreement is limited to the fees paid in the three (3) months preceding the claim. Agency does not guarantee specific advertising results.\n\n`;

  md += `## 10. Signatures\n\n`;
  md += `| | Agency | Client |\n|---|---|---|\n`;
  md += `| Name | ${agency.name} | ${client.contact_name || "______________________"} |\n`;
  md += `| Signature | ______________________ | ______________________ |\n`;
  md += `| Date | ______________________ | ______________________ |\n`;
  return md;
}

/* ─────────────────────────── HTML (primary) ──────────────────────────── */

/** Contract-specific components, all on --ds-* tokens (no raw hex, no forked palette). */
function contractCss() {
  return `
.doc-legal{counter-reset:clause;}
.doc-clause{background:var(--ds-surface);border:1px solid var(--ds-line);border-radius:var(--ds-r);
  padding:20px 24px 20px 64px;box-shadow:var(--ds-shadow-sm);margin:12px 0;position:relative;}
.doc-clause::before{counter-increment:clause;content:counter(clause);position:absolute;left:20px;top:20px;
  width:30px;height:30px;border-radius:50%;background-image:var(--ds-grad-brand);color:#fff;
  display:grid;place-items:center;font-weight:700;font-size:14px;font-variant-numeric:tabular-nums;}
.doc-clause h3{margin:2px 0 8px;font-size:16px;}
.doc-clause p,.doc-clause ul{margin:6px 0;font-size:14px;color:var(--ds-ink-2);}
.doc-clause ul{padding-left:20px;}
.doc-fees{display:grid;grid-template-columns:1fr auto;gap:8px 20px;font-size:14px;margin-top:6px;}
.doc-fees .lbl{color:var(--ds-ink-2);} .doc-fees .amt{font-weight:700;font-variant-numeric:tabular-nums;text-align:right;}
.doc-sign{display:grid;grid-template-columns:1fr 1fr;gap:44px;margin-top:8px;}
.doc-sign__party{font-size:11px;font-weight:700;letter-spacing:.08em;text-transform:uppercase;color:var(--ds-muted);margin-bottom:34px;}
.doc-sign__line{border-top:1.5px solid var(--ds-ink);padding-top:8px;font-size:12.5px;color:var(--ds-muted);}
.doc-sign__line + .doc-sign__line{margin-top:30px;}
@media (max-width:640px){.doc-sign{grid-template-columns:1fr;gap:24px;}.doc-fees{grid-template-columns:1fr;}}
`;
}

function clause(title, bodyHtml) {
  return `<div class="doc-clause"><h3>${escHtml(title)}</h3>${bodyHtml}</div>`;
}

export function buildContractHtml({ agency, client, pkg, retainer, terms, date, proposalAccepted, addons, currency }) {
  const cur = currency || pkg.currency;
  const monthly = retainer > 0 ? retainer : pkg.monthly_retainer;
  const money = (n) => `${cur} ${Number(n || 0).toLocaleString()}`;
  const addonRows = (addons || []).map((a) => `<div class="lbl">${escHtml(a.name)} (due on signing)</div><div class="amt">${money(a.amount)}</div>`).join("");

  const hero = heroHeader({
    title: "Service Agreement",
    eyebrow: `Service Agreement · ${agency.name}`,
    subtitleHtml: `Between <strong>${escHtml(agency.name)}</strong> and <strong>${escHtml(client.company)}</strong> &nbsp;·&nbsp; Effective ${escHtml(date)}`,
    headline: "Social media management retainer. Plain-language terms, ready to sign.",
    pills: [`Package · ${pkg.name}`, `Retainer · ${money(monthly)}/mo`, `Term · ${terms.contract_length_months} months`],
  });

  const attorney = `<div class="ds-callout ds-callout--warn"><strong>Template — not legal advice.</strong> Generated by ${escHtml(agency.name)}'s system for convenience. Have a qualified attorney review before signing.</div>`;

  const recap = proposalAccepted
    ? `<p class="ds-caption" style="margin:0 0 4px">This agreement formalizes the ${escHtml(pkg.name)} proposal.</p>` : "";

  const clauses = [
    clause("Parties", `<p>This agreement is between <strong>${escHtml(agency.name)}</strong> ("Agency", ${escHtml(agency.email)}) and <strong>${escHtml(client.company)}</strong> ("Client"${client.contact_name ? `, represented by ${escHtml(client.contact_name)}` : ""}${client.contact_email ? `, ${escHtml(client.contact_email)}` : ""}).</p>`),
    clause("Services", `<p>Agency will provide the <strong>${escHtml(pkg.name)}</strong> package:</p><ul>${(pkg.includes || []).map((i) => `<li>${escHtml(i)}</li>`).join("")}</ul>`),
    clause("Fees", `<div class="doc-fees">
<div class="lbl">Monthly management retainer (due in advance)</div><div class="amt">${money(monthly)}</div>
<div class="lbl">One-time setup fee (due on signing)</div><div class="amt">${money(pkg.setup_fee)}</div>
${addonRows}
<div class="lbl">Ad spend</div><div class="amt" style="font-weight:500">${escHtml(terms.ad_spend)}</div>
</div>`),
    clause("Term &amp; Renewal", `<p>Initial term of <strong>${terms.contract_length_months} months</strong> from the effective date, renewing month-to-month thereafter unless cancelled.</p>`),
    clause("Payment", `<p>${escHtml(terms.payment)}</p>`),
    clause("Cancellation", `<p>${escHtml(terms.cancellation)}</p>`),
    clause("Intellectual Property", `<p>Client owns its ad accounts, pages, pixels, brand assets, and all work product delivered and paid for. Agency retains ownership of its tools, processes, and the platform used to deliver the services.</p>`),
    clause("Confidentiality", `<p>Each party will keep the other's non-public information confidential and use it only to perform this agreement.</p>`),
    clause("Limitation of Liability", `<p>Agency's total liability under this agreement is limited to the fees paid in the three (3) months preceding the claim. Agency does not guarantee specific advertising results.</p>`),
  ].join("\n");

  const signatures = `<div class="ds-card"><div class="doc-sign">
<div><div class="doc-sign__party">Agency</div><div class="doc-sign__line">${escHtml(agency.name)}</div><div class="doc-sign__line">Signature</div><div class="doc-sign__line">Date</div></div>
<div><div class="doc-sign__party">Client — ${escHtml(client.company)}</div><div class="doc-sign__line">${escHtml(client.contact_name || "Name")}</div><div class="doc-sign__line">Signature</div><div class="doc-sign__line">Date</div></div>
</div></div>`;

  const body = [
    hero,
    attorney,
    recap,
    `<div class="doc-legal">${clauses}</div>`,
    docSection({ id: "signatures", eyebrow: "Signatures", title: "Acceptance", sub: "Signing below binds both parties to the terms above.", body: signatures }),
  ].filter(Boolean).join("\n");

  return docShell({ title: `${client.company} — Service Agreement`, extraCss: contractCss(), body, date });
}

/**
 * Best-effort e-signature send. Supports Dropbox Sign when DROPBOX_SIGN_API_KEY is
 * set; otherwise returns a manual result. The live call is wrapped fail-closed —
 * any error falls back to manual rather than claiming success.
 */
export async function sendForSignature({ pdfPath, client, agency }) {
  const key = process.env.DROPBOX_SIGN_API_KEY;
  if (!key) {
    return { sent: false, mode: "manual", reason: "No DROPBOX_SIGN_API_KEY set — send the PDF for signature manually (or set a provider key)." };
  }
  if (!client.contact_email) {
    return { sent: false, mode: "manual", reason: "No client contact email on the deal — set it before an e-sign send." };
  }
  try {
    // Dropbox Sign signature_request/send_with_file (multipart). Unverified against
    // the live API — treat a 2xx as sent, anything else as manual fallback.
    const form = new FormData();
    form.append("title", `${agency.name} — Service Agreement`);
    form.append("subject", "Your service agreement is ready to sign");
    form.append("signers[0][email_address]", client.contact_email);
    form.append("signers[0][name]", client.contact_name || client.company);
    form.append("file[0]", new Blob([readFileSync(pdfPath)], { type: "application/pdf" }), "agreement.pdf");
    const res = await fetch("https://api.hellosign.com/v3/signature_request/send", {
      method: "POST",
      headers: { Authorization: "Basic " + Buffer.from(`${key}:`).toString("base64") },
      body: form,
    });
    if (!res.ok) {
      const t = await res.text().catch(() => "");
      return { sent: false, mode: "manual", reason: `Dropbox Sign ${res.status}: ${t.slice(0, 200)} — sending manually` };
    }
    const json = await res.json().catch(() => ({}));
    return { sent: true, mode: "dropbox_sign", request_id: json?.signature_request?.signature_request_id || null };
  } catch (e) {
    return { sent: false, mode: "manual", reason: `e-sign send failed (${e.message}) — send the PDF manually` };
  }
}

async function main() {
  const args = process.argv.slice(2);
  const slug = args[0];
  if (!slug) { console.error("Usage: contract.js <slug> [--package id] [--send] [--mark-signed]"); process.exit(1); }

  const d = getDeal(slug);
  if (!d) { console.error(`No CRM deal for "${slug}". Run /crm add ${slug} (and /proposal) first.`); process.exit(2); }

  // --mark-signed: record the signature and move the deal to won (validator requires
  // a proposal link, so a deal can't be "won" without the paper trail).
  if (args.includes("--mark-signed")) {
    if (!d.links.contract) { console.error("No contract generated yet — run /contract first, then --mark-signed."); process.exit(3); }
    if (!dealSchema.isValidTransition(d.stage, "won") && d.stage !== "won") {
      console.error(`Cannot mark signed from stage "${d.stage}" (need proposed/negotiating). Advance the deal first.`); process.exit(4);
    }
    try {
      const saved = await upsertDeal(slug, {
        stage: "won", won_at: nowIso(),
        activities: [...(d.activities || []), { at: nowIso(), type: "contract", note: "agreement signed" }],
      });
      console.log(JSON.stringify({ slug, stage: saved.stage, signed: true, next: "Run /intake to onboard, then /billing to invoice." }, null, 2));
    } catch (e) { console.error(`Could not mark won: ${e.message}`); process.exit(5); }
    return;
  }

  // Generate the agreement.
  const catalog = loadCatalog();
  const pkgIdx = args.indexOf("--package");
  const pkg = pickPackage(catalog, { packageId: pkgIdx >= 0 ? args[pkgIdx + 1] : null, retainer: d.deal.monthly_retainer });
  const client = { company: d.company_name, contact_name: d.contact.name, contact_email: d.contact.email };
  // The deal's currency wins over the catalog package's, so the retainer and the
  // one-time line items are always quoted in the same currency the client is billed in.
  const contractArgs = { agency: catalog.agency, client, pkg, retainer: d.deal.monthly_retainer, terms: catalog.terms, date: today(), addons: d.deal.addons || [], currency: d.deal.currency || pkg.currency };
  const md = buildContractMarkdown(contractArgs);
  const outDir = resolve(ROOT, "contracts", slug);
  mkdirSync(outDir, { recursive: true });
  const mdPath = resolve(outDir, "agreement.md");
  writeFileSync(mdPath, md);
  // Primary deliverable: structured HTML on the design system (+ PDF). Markdown twin kept above.
  const html = buildContractHtml({ ...contractArgs, proposalAccepted: !!d.links?.proposal });
  const htmlPath = resolve(outDir, "agreement.html");
  const { pdfPath, pdfOk } = writeDocHtmlAndPdf(htmlPath, html);

  // Advance proposed → negotiating when a contract goes out (state machine permitting).
  const stage = dealSchema.isValidTransition(d.stage, "negotiating") ? "negotiating" : d.stage;
  const link = pdfOk ? `contracts/${slug}/agreement.pdf` : `contracts/${slug}/agreement.html`;
  await upsertDeal(slug, {
    stage,
    links: { contract: link },
    activities: [...(d.activities || []), { at: nowIso(), type: "contract", note: `agreement generated (${pkg.name})` }],
  });

  let esign = { sent: false, mode: "skipped" };
  if (args.includes("--send")) {
    esign = await sendForSignature({ pdfPath: pdfOk ? pdfPath : htmlPath, client: { company: d.company_name, contact_name: d.contact.name, contact_email: d.contact.email }, agency: catalog.agency });
  }

  console.log(JSON.stringify({
    slug, company: d.company_name, package: pkg.id,
    html: htmlPath, pdf: pdfOk ? pdfPath : "(PDF skipped — install playwright)",
    crm_stage: stage, contract_link: link, esign,
    note: "Template — have an attorney review before signing.",
    next: args.includes("--send") ? "After the client signs: /contract " + slug + " --mark-signed" : "Send it, then /contract " + slug + " --mark-signed on signature.",
  }, null, 2));
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main().catch((e) => { console.error("[contract] FATAL:", e.message); process.exit(1); });
}
