#!/usr/bin/env node
/**
 * /contract companion (Phase 5) — generates the service agreement from an accepted
 * proposal, optionally sends it for e-signature, and on signature advances the CRM
 * deal to `won`.
 *
 * Honest about scope, like the rest of smOS:
 *  - The contract is a TEMPLATE, not legal advice — output says so; have an attorney review.
 *  - E-sign is best-effort: with a provider key set it attempts a real send; otherwise
 *    it falls back to a manual signature block. (Live provider call is unverified — it
 *    fail-closes to manual on any error rather than pretending it sent.)
 *
 * Usage:
 *   node skills/contract/contract.js <slug> [--package growth]   # generate + link to CRM
 *   node skills/contract/contract.js <slug> --send               # also send for e-signature
 *   node skills/contract/contract.js <slug> --mark-signed        # record signature → deal won
 */
import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { loadEnv } from "../../scripts/lib/load-env.js";
import { writeHtmlAndPdf } from "../../scripts/lib/md_to_html.js";
import { getDeal, upsertDeal } from "../../scripts/lib/crm-store.js";
import { deal as dealSchema } from "../../schemas/index.js";
import { loadCatalog, pickPackage } from "../proposal/proposal.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "../..");
loadEnv();

const nowIso = () => new Date().toISOString();
const today = () => nowIso().slice(0, 10);

export function buildContractMarkdown({ agency, client, pkg, retainer, terms, date }) {
  const cur = pkg.currency;
  const monthly = retainer > 0 ? retainer : pkg.monthly_retainer;
  let md = `# Social Media Management Agreement\n\n`;
  md += `_Effective ${date}_\n\n`;
  md += `> Template generated by smOS. This is not legal advice — have a qualified attorney review before signing.\n\n---\n\n`;

  md += `## 1. Parties\n\n`;
  md += `This agreement is between **${agency.name}** ("Agency", ${agency.email}) and **${client.company}** ("Client"${client.contact_name ? `, represented by ${client.contact_name}` : ""}${client.contact_email ? `, ${client.contact_email}` : ""}).\n\n`;

  md += `## 2. Services\n\n`;
  md += `Agency will provide the **${pkg.name}** package:\n\n${(pkg.includes || []).map((i) => `- ${i}`).join("\n")}\n\n`;

  md += `## 3. Fees\n\n`;
  md += `- **Monthly management retainer:** ${cur} ${monthly.toLocaleString()}, due monthly in advance.\n`;
  md += `- **One-time setup fee:** ${cur} ${(pkg.setup_fee || 0).toLocaleString()}, due on signing.\n`;
  md += `- **Ad spend:** ${terms.ad_spend}\n\n`;

  md += `## 4. Term & Renewal\n\n`;
  md += `Initial term of **${terms.contract_length_months} months** from the effective date, renewing month-to-month thereafter unless cancelled.\n\n`;

  md += `## 5. Payment\n\n${terms.payment}\n\n`;
  md += `## 6. Cancellation\n\n${terms.cancellation}\n\n`;

  md += `## 7. Intellectual Property\n\n`;
  md += `Client owns its ad accounts, pages, pixels, brand assets, and all work product delivered and paid for. Agency retains ownership of its tools, processes, and the smOS platform used to deliver the services.\n\n`;

  md += `## 8. Confidentiality\n\n`;
  md += `Each party will keep the other's non-public information confidential and use it only to perform this agreement.\n\n`;

  md += `## 9. Limitation of Liability\n\n`;
  md += `Agency's total liability under this agreement is limited to the fees paid in the three (3) months preceding the claim. Agency does not guarantee specific advertising results.\n\n`;

  md += `## 10. Signatures\n\n`;
  md += `| | Agency | Client |\n|---|---|---|\n`;
  md += `| Name | ${agency.name} | ${client.contact_name || "______________________"} |\n`;
  md += `| Signature | ______________________ | ______________________ |\n`;
  md += `| Date | ______________________ | ______________________ |\n`;
  return md;
}

/**
 * Best-effort e-signature send. Supports Dropbox Sign when DROPBOX_SIGN_API_KEY is
 * set; otherwise returns a manual result. The live call is wrapped fail-closed —
 * any error falls back to manual rather than claiming success.
 */
export async function sendForSignature({ pdfPath, client, agency }) {
  const key = process.env.DROPBOX_SIGN_API_KEY;
  if (!key) {
    return { sent: false, mode: "manual", reason: "No DROPBOX_SIGN_API_KEY set — send the PDF for signature manually (or set a provider key)." };
  }
  if (!client.contact_email) {
    return { sent: false, mode: "manual", reason: "No client contact email on the deal — set it before an e-sign send." };
  }
  try {
    // Dropbox Sign signature_request/send_with_file (multipart). Unverified against
    // the live API — treat a 2xx as sent, anything else as manual fallback.
    const form = new FormData();
    form.append("title", `${agency.name} — Service Agreement`);
    form.append("subject", "Your service agreement is ready to sign");
    form.append("signers[0][email_address]", client.contact_email);
    form.append("signers[0][name]", client.contact_name || client.company);
    form.append("file[0]", new Blob([readFileSync(pdfPath)], { type: "application/pdf" }), "agreement.pdf");
    const res = await fetch("https://api.hellosign.com/v3/signature_request/send", {
      method: "POST",
      headers: { Authorization: "Basic " + Buffer.from(`${key}:`).toString("base64") },
      body: form,
    });
    if (!res.ok) {
      const t = await res.text().catch(() => "");
      return { sent: false, mode: "manual", reason: `Dropbox Sign ${res.status}: ${t.slice(0, 200)} — sending manually` };
    }
    const json = await res.json().catch(() => ({}));
    return { sent: true, mode: "dropbox_sign", request_id: json?.signature_request?.signature_request_id || null };
  } catch (e) {
    return { sent: false, mode: "manual", reason: `e-sign send failed (${e.message}) — send the PDF manually` };
  }
}

async function main() {
  const args = process.argv.slice(2);
  const slug = args[0];
  if (!slug) { console.error("Usage: contract.js <slug> [--package id] [--send] [--mark-signed]"); process.exit(1); }

  const d = getDeal(slug);
  if (!d) { console.error(`No CRM deal for "${slug}". Run /crm add ${slug} (and /proposal) first.`); process.exit(2); }

  // --mark-signed: record the signature and move the deal to won (validator requires
  // a proposal link, so a deal can't be "won" without the paper trail).
  if (args.includes("--mark-signed")) {
    if (!d.links.contract) { console.error("No contract generated yet — run /contract first, then --mark-signed."); process.exit(3); }
    if (!dealSchema.isValidTransition(d.stage, "won") && d.stage !== "won") {
      console.error(`Cannot mark signed from stage "${d.stage}" (need proposed/negotiating). Advance the deal first.`); process.exit(4);
    }
    try {
      const saved = await upsertDeal(slug, {
        stage: "won", won_at: nowIso(),
        activities: [...(d.activities || []), { at: nowIso(), type: "contract", note: "agreement signed" }],
      });
      console.log(JSON.stringify({ slug, stage: saved.stage, signed: true, next: "Run /intake to onboard, then /billing to invoice." }, null, 2));
    } catch (e) { console.error(`Could not mark won: ${e.message}`); process.exit(5); }
    return;
  }

  // Generate the agreement.
  const catalog = loadCatalog();
  const pkgIdx = args.indexOf("--package");
  const pkg = pickPackage(catalog, { packageId: pkgIdx >= 0 ? args[pkgIdx + 1] : null, retainer: d.deal.monthly_retainer });
  const md = buildContractMarkdown({
    agency: catalog.agency,
    client: { company: d.company_name, contact_name: d.contact.name, contact_email: d.contact.email },
    pkg, retainer: d.deal.monthly_retainer, terms: catalog.terms, date: today(),
  });
  const outDir = resolve(ROOT, "contracts", slug);
  mkdirSync(outDir, { recursive: true });
  const mdPath = resolve(outDir, "agreement.md");
  writeFileSync(mdPath, md);
  const { htmlPath, pdfPath, pdfOk } = writeHtmlAndPdf(mdPath, md, { title: `${d.company_name} — Service Agreement` });

  // Advance proposed → negotiating when a contract goes out (state machine permitting).
  const stage = dealSchema.isValidTransition(d.stage, "negotiating") ? "negotiating" : d.stage;
  const link = pdfOk ? `contracts/${slug}/agreement.pdf` : `contracts/${slug}/agreement.html`;
  await upsertDeal(slug, {
    stage,
    links: { contract: link },
    activities: [...(d.activities || []), { at: nowIso(), type: "contract", note: `agreement generated (${pkg.name})` }],
  });

  let esign = { sent: false, mode: "skipped" };
  if (args.includes("--send")) {
    esign = await sendForSignature({ pdfPath: pdfOk ? pdfPath : htmlPath, client: { company: d.company_name, contact_name: d.contact.name, contact_email: d.contact.email }, agency: catalog.agency });
  }

  console.log(JSON.stringify({
    slug, company: d.company_name, package: pkg.id,
    html: htmlPath, pdf: pdfOk ? pdfPath : "(PDF skipped — install playwright)",
    crm_stage: stage, contract_link: link, esign,
    note: "Template — have an attorney review before signing.",
    next: args.includes("--send") ? "After the client signs: /contract " + slug + " --mark-signed" : "Send it, then /contract " + slug + " --mark-signed on signature.",
  }, null, 2));
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main().catch((e) => { console.error("[contract] FATAL:", e.message); process.exit(1); });
}
