#!/usr/bin/env node
/**
 * /brand-book companion — deterministic assembler. Formats the locked brand_profile
 * layers into a brand guidelines doc (MD → HTML + PDF) and records the metadata.
 * Generates no brand decisions; halts (fail-closed) if a required field is missing.
 *
 * Usage: node skills/brand-book/brand-book.js <slug>
 */
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { loadBrand, saveBrand, clientDir } from "../../scripts/lib/brand.js";
import { writeHtmlAndPdf } from "../../scripts/lib/md_to_html.js";
import * as brandProfile from "../../schemas/brand_profile.js";

function line(label, val) { return val ? `- **${label}:** ${val}\n` : ""; }
function list(items) { return (items || []).map((i) => `- ${typeof i === "string" ? i : JSON.stringify(i)}`).join("\n"); }

function buildMarkdown(b) {
  const s = b.strategy, v = b.verbal, vis = b.visual;
  const name = v.name || b.client_slug;
  let md = `# ${name} — Brand Guidelines\n\n`;
  md += `_Version ${new Date().toISOString().slice(0, 10)} · generated by smOS_\n\n`;

  md += `## 1 · Brand Strategy\n\n`;
  md += line("Purpose", s.purpose) + line("Mission", s.mission) + line("Vision", s.vision);
  md += line("Positioning", s.positioning_statement);
  md += line("Archetype", [s.archetype.primary, s.archetype.secondary].filter(Boolean).join(" + "));
  md += line("Value proposition", s.value_proposition) + line("Differentiation", s.differentiation);
  md += line("Essence", s.essence) + line("Promise", s.promise);
  if (s.values?.length) md += `\n**Values**\n${list(s.values)}\n`;
  if (s.messaging_pillars?.length) md += `\n**Messaging pillars**\n${list(s.messaging_pillars)}\n`;

  md += `\n## 2 · Logo System\n\n`;
  md += line("Primary", vis.logo.primary_url) + line("Mark / icon", vis.logo.mark_url);
  md += line("Wordmark", vis.logo.wordmark_url) + line("Monochrome", vis.logo.mono_url);
  md += line("White / reversed", vis.logo.reverse_url) + line("Vector (SVG)", vis.logo.svg_url);
  md += line("Clear space", vis.logo.clear_space) + line("Minimum size", vis.logo.min_size);

  md += `\n## 3 · Color Palette\n\n`;
  md += line("Primary", vis.colors.primary) + line("Secondary", vis.colors.secondary) + line("Accent", vis.colors.accent);
  if (vis.colors.neutrals?.length) md += `\n**Neutrals**\n${list(vis.colors.neutrals)}\n`;
  md += `\nUsage ratio **60-30-10** (primary / secondary / accent). Maintain WCAG AA contrast (4.5:1 body, 3:1 large text).\n`;

  md += `\n## 4 · Typography\n\n`;
  md += line("Heading", vis.typography.heading) + line("Body", vis.typography.body) + line("Scale", vis.typography.scale);

  md += `\n## 5 · Imagery & Iconography\n\n`;
  md += line("Imagery style", vis.imagery_style) + line("Iconography", vis.iconography);

  md += `\n## 6 · Voice & Tone\n\n`;
  if (v.voice.traits?.length) md += `**Traits**\n${list(v.voice.traits)}\n\n`;
  if (v.voice.do?.length) md += `**Do**\n${list(v.voice.do)}\n\n`;
  if (v.voice.dont?.length) md += `**Don't**\n${list(v.voice.dont)}\n\n`;
  if (v.messaging_house.roof) {
    md += `**Messaging house**\n`;
    md += line("Roof", v.messaging_house.roof);
    if (v.messaging_house.walls?.length) md += `\nWalls:\n${list(v.messaging_house.walls)}\n`;
    if (v.messaging_house.foundation?.length) md += `\nFoundation:\n${list(v.messaging_house.foundation)}\n`;
  }
  md += line("\nTagline", v.tagline) + line("Boilerplate", v.boilerplate);

  md += `\n## 7 · AI-Content Disclosure\n\n`;
  md += vis.ai_generated
    ? `This brand's visual assets include AI-generated imagery. Per Meta policy (since Mar 2026), any ad built from these assets MUST set \`ai_disclosed: true\` — the smOS \`ai-disclosure\` guard fail-closed blocks undisclosed AI creatives. Purely-AI logos generally cannot be copyrighted without human modification; the mark remains trademarkable (clearance still required).\n`
    : `Brand visuals are human-authored. If AI imagery is introduced later, set \`visual.ai_generated: true\` so the smOS \`ai-disclosure\` guard carries the disclosure through to ads.\n`;

  md += `\n## 8 · Governance\n\n`;
  md += `- File naming: \`{slug}_{asset}_{variant}_{version}\`\n- Always use ™/® per the legal status of the mark\n- Logo, color, and name changes require the same human-approval gate as their originating skill\n- Brand assets live in \`clients/${b.client_slug}/brand/\`\n`;

  return md;
}

function main() {
  const slug = process.argv[2];
  if (!slug) { console.error("Usage: brand-book.js <slug>"); process.exit(1); }

  const b = loadBrand(slug);
  const v = brandProfile.validate(b, { stage: "guidelines" });
  if (!v.ok) { console.error(`Cannot build brand book:\n  - ${v.errors.join("\n  - ")}`); process.exit(3); }

  const md = buildMarkdown(b);
  const mdPath = resolve(clientDir(slug), "brand_book.md");
  writeFileSync(mdPath, md);
  const { htmlPath, pdfPath, pdfOk } = writeHtmlAndPdf(mdPath, md, { title: `${b.verbal.name || slug} — Brand Guidelines` });

  const out = saveBrand(slug, {
    guidelines: { doc_url: htmlPath, pdf_url: pdfOk ? pdfPath : null, version: new Date().toISOString().slice(0, 10), generated_at: new Date().toISOString() },
  });

  console.log(JSON.stringify({ slug, html: htmlPath, pdf: pdfOk ? pdfPath : "(PDF render skipped — install playwright)", status: out.status, next: "/brand-social" }, null, 2));
}

main();
